const community = [
  {
    id: 42,
    title: '스마트워치에 이런 기능이 있으면 좋겠어요',
    category: '전자제품',
    author: '김아이디어',
    date: '2024.01.15',
    views: 156,
    likes: 12,
    content: '전자제품에 대한 아이디어',
    type: '아이디어',
  },
  {
    id: 41,
    title: '무선 이어폰 후기 - 가격 대비 만족',
    category: '생활용품',
    author: '박후기',
    date: '2024.01.14',
    views: 234,
    likes: 18,
    content: '무선 이어폰에 대한 후기',
    type: '후기',
  },
  {
    id: 40,
    title: 'AI 스피커로 집안을 스마트하게 만들어보세요',
    category: '전자제품',
    author: '이스마트',
    date: '2024.01.13',
    views: 89,
    likes: 7,
    content: 'AI 스피커 활용법에 대한 팁',
    type: '아이디어',
  },
  {
    id: 39,
    title: '블루투스 키보드 추천해주세요',
    category: '전자제품',
    author: '최키보드',
    date: '2024.01.12',
    views: 145,
    likes: 9,
    content: '블루투스 키보드 구매 고민',
    type: '아이디어',
  },
  {
    id: 38,
    title: '무선 충전기 사용 후기',
    category: '생활용품',
    author: '정충전',
    date: '2024.01.11',
    views: 78,
    likes: 5,
    content: '무선 충전기 사용 경험담',
    type: '후기',
  },
  {
    id: 37,
    title: '스마트폰 케이스 추천',
    category: '생활용품',
    author: '한케이스',
    date: '2024.01.10',
    views: 203,
    likes: 15,
    content: '좋은 스마트폰 케이스 찾기',
    type: '아이디어',
  },
  {
    id: 36,
    title: '게이밍 마우스 어떤 걸 사야 할까요?',
    category: '전자제품',
    author: '오게임',
    date: '2024.01.09',
    views: 167,
    likes: 11,
    content: '게이밍 마우스 선택 고민',
    type: '아이디어',
  },
  {
    id: 35,
    title: '노트북 쿨러 패드 사용해보신 분 있나요?',
    category: '전자제품',
    author: '서쿨러',
    date: '2024.01.08',
    views: 92,
    likes: 6,
    content: '노트북 쿨러 패드 효과 문의',
    type: '아이디어',
  },
  {
    id: 34,
    title: '블루투스 헤드셋 음질 비교',
    category: '전자제품',
    author: '강음질',
    date: '2024.01.07',
    views: 134,
    likes: 8,
    content: '블루투스 헤드셋 음질 리뷰',
    type: '후기',
  },
  {
    id: 33,
    title: '스마트 홈 디바이스 설정 방법',
    category: '전자제품',
    author: '윤홈',
    date: '2024.01.06',
    views: 189,
    likes: 13,
    content: '스마트 홈 구축 가이드',
    type: '아이디어',
  },
  {
    id: 32,
    title: '무선 마우스 배터리 수명은 어느 정도인가요?',
    category: '전자제품',
    author: '배터리',
    date: '2024.01.05',
    views: 76,
    likes: 4,
    content: '무선 마우스 배터리 관련 문의',
    type: '아이디어',
  },
  {
    id: 31,
    title: '태블릿 PC 추천해주세요',
    category: '전자제품',
    author: '태블릿',
    date: '2024.01.04',
    views: 245,
    likes: 19,
    content: '태블릿 PC 구매 고민',
    type: '아이디어',
  },
  {
    id: 30,
    title: '스마트워치 앱 추천',
    category: '전자제품',
    author: '앱추천',
    date: '2024.01.03',
    views: 98,
    likes: 7,
    content: '유용한 스마트워치 앱 소개',
    type: '아이디어',
  },
  {
    id: 29,
    title: '무선 이어폰 방수 기능 테스트',
    category: '전자제품',
    author: '방수테스트',
    date: '2024.01.02',
    views: 156,
    likes: 10,
    content: '무선 이어폰 방수 성능 리뷰',
    type: '후기',
  },
  {
    id: 28,
    title: '블루투스 스피커 음질 비교',
    category: '전자제품',
    author: '스피커음질',
    date: '2024.01.01',
    views: 178,
    likes: 12,
    content: '블루투스 스피커 음질 테스트',
    type: '후기',
  },
  {
    id: 27,
    title: '스마트폰 카메라 렌즈 부착 후기',
    category: '전자제품',
    author: '카메라렌즈',
    date: '2023.12.31',
    views: 112,
    likes: 8,
    content: '스마트폰 카메라 렌즈 사용기',
    type: '후기',
  },
  {
    id: 26,
    title: '무선 충전 패드 여러 개 동시 사용',
    category: '전자제품',
    author: '충전패드',
    date: '2023.12.30',
    views: 67,
    likes: 3,
    content: '무선 충전 패드 다중 사용 경험',
    type: '후기',
  },
  {
    id: 25,
    title: '게이밍 키보드 기계식 vs 멤브레인',
    category: '전자제품',
    author: '키보드비교',
    date: '2023.12.29',
    views: 198,
    likes: 14,
    content: '게이밍 키보드 타입별 비교',
    type: '후기',
  },
  {
    id: 24,
    title: '스마트워치 배터리 절약 팁',
    category: '전자제품',
    author: '배터리절약',
    date: '2023.12.28',
    views: 143,
    likes: 9,
    content: '스마트워치 배터리 수명 연장 방법',
    type: '아이디어',
  },
  {
    id: 23,
    title: '블루투스 이어폰 연결 문제 해결법',
    category: '전자제품',
    author: '연결문제',
    date: '2023.12.27',
    views: 89,
    likes: 6,
    content: '블루투스 이어폰 연결 오류 해결',
    type: '아이디어',
  },
  {
    id: 22,
    title: '무선 마우스 지연시간 개선 방법',
    category: '전자제품',
    author: '지연개선',
    date: '2023.12.26',
    views: 124,
    likes: 7,
    content: '무선 마우스 반응속도 향상 팁',
    type: '아이디어',
  },
  {
    id: 21,
    title: '스마트 홈 보안 시스템 구축기',
    category: '전자제품',
    author: '홈보안',
    date: '2023.12.25',
    views: 167,
    likes: 11,
    content: '스마트 홈 보안 시스템 설치 경험',
    type: '후기',
  },
  {
    id: 20,
    title: 'VR 헤드셋으로 게임하는 경험',
    category: '전자제품',
    author: 'VR게이머',
    date: '2023.12.24',
    views: 298,
    likes: 22,
    content: 'VR 헤드셋 게임 플레이 후기',
    type: '후기',
  },
  {
    id: 19,
    title: '드론 촬영으로 만든 영상 공유',
    category: '전자제품',
    author: '드론촬영',
    date: '2023.12.23',
    views: 445,
    likes: 35,
    content: '드론으로 촬영한 풍경 영상',
    type: '후기',
  },
  {
    id: 18,
    title: '스마트 미러 만들기 프로젝트',
    category: '전자제품',
    author: '미러제작',
    date: '2023.12.22',
    views: 189,
    likes: 16,
    content: 'DIY 스마트 미러 제작 과정',
    type: '아이디어',
  },
  {
    id: 17,
    title: '로봇 청소기 성능 비교 분석',
    category: '생활용품',
    author: '청소로봇',
    date: '2023.12.21',
    views: 267,
    likes: 20,
    content: '다양한 로봇 청소기 성능 테스트',
    type: '후기',
  },
  {
    id: 16,
    title: '3D 프린터로 만든 작품들',
    category: '전자제품',
    author: '3D프린터',
    date: '2023.12.20',
    views: 156,
    likes: 12,
    content: '3D 프린터로 제작한 다양한 작품',
    type: '후기',
  },
  {
    id: 15,
    title: '스마트 도어락 설치 후기',
    category: '생활용품',
    author: '도어락',
    date: '2023.12.19',
    views: 134,
    likes: 9,
    content: '스마트 도어락 설치 및 사용 경험',
    type: '후기',
  },
  {
    id: 14,
    title: '무선 라우터 속도 개선 방법',
    category: '전자제품',
    author: '라우터속도',
    date: '2023.12.18',
    views: 178,
    likes: 13,
    content: 'WiFi 속도 향상을 위한 설정 팁',
    type: '아이디어',
  },
  {
    id: 13,
    title: '스마트 전구로 분위기 연출하기',
    category: '생활용품',
    author: '전구분위기',
    date: '2023.12.17',
    views: 98,
    likes: 7,
    content: '스마트 전구 활용한 인테리어',
    type: '아이디어',
  },
  {
    id: 12,
    title: '블루투스 자동차 오디오 설치',
    category: '전자제품',
    author: '카오디오',
    date: '2023.12.16',
    views: 223,
    likes: 17,
    content: '차량용 블루투스 오디오 설치기',
    type: '후기',
  },
  {
    id: 11,
    title: '스마트 워치 운동 추적 기능',
    category: '전자제품',
    author: '운동추적',
    date: '2023.12.15',
    views: 145,
    likes: 10,
    content: '스마트워치 운동 데이터 분석',
    type: '후기',
  },
  {
    id: 10,
    title: '무선 충전기 여러 개 동시 사용법',
    category: '전자제품',
    author: '충전다중',
    date: '2023.12.14',
    views: 87,
    likes: 5,
    content: '여러 기기 동시 무선 충전 팁',
    type: '아이디어',
  },
  {
    id: 9,
    title: '스마트 스피커 음성 인식 테스트',
    category: '전자제품',
    author: '음성인식',
    date: '2023.12.13',
    views: 112,
    likes: 8,
    content: '스마트 스피커 음성 인식 정확도',
    type: '후기',
  },
  {
    id: 8,
    title: '블루투스 이어폰 노이즈 캔슬링 비교',
    category: '전자제품',
    author: '노이즈캔슬',
    date: '2023.12.12',
    views: 189,
    likes: 14,
    content: 'ANC 기능이 있는 이어폰 비교',
    type: '후기',
  },
  {
    id: 7,
    title: '스마트 홈 센서 설치 가이드',
    category: '전자제품',
    author: '홈센서',
    date: '2023.12.11',
    views: 156,
    likes: 11,
    content: '다양한 스마트 홈 센서 설치법',
    type: '아이디어',
  },
  {
    id: 6,
    title: '무선 마우스 에너지 절약 모드',
    category: '전자제품',
    author: '마우스절약',
    date: '2023.12.10',
    views: 76,
    likes: 4,
    content: '무선 마우스 배터리 절약 팁',
    type: '아이디어',
  },
  {
    id: 5,
    title: '스마트폰 카메라 삼각대 추천',
    category: '생활용품',
    author: '삼각대',
    date: '2023.12.09',
    views: 134,
    likes: 9,
    content: '스마트폰용 삼각대 선택 가이드',
    type: '아이디어',
  },
  {
    id: 4,
    title: '블루투스 키보드 한글 입력 속도',
    category: '전자제품',
    author: '키보드속도',
    date: '2023.12.08',
    views: 98,
    likes: 6,
    content: '블루투스 키보드 타이핑 속도 테스트',
    type: '후기',
  },
  {
    id: 3,
    title: '스마트워치 알림 설정 최적화',
    category: '전자제품',
    author: '알림최적화',
    date: '2023.12.07',
    views: 167,
    likes: 12,
    content: '스마트워치 알림 효율적 관리법',
    type: '아이디어',
  },
  {
    id: 2,
    title: '무선 이어폰 통화 품질 비교',
    category: '전자제품',
    author: '통화품질',
    date: '2023.12.06',
    views: 145,
    likes: 10,
    content: '무선 이어폰 통화 음질 테스트',
    type: '후기',
  },
  {
    id: 1,
    title: '스마트 홈 자동화 시나리오 설정',
    category: '전자제품',
    author: '자동화시나리오',
    date: '2023.12.05',
    views: 198,
    likes: 15,
    content: '스마트 홈 자동화 루틴 만들기',
    type: '아이디어',
  },
];

export default community;